Events
APIStear/FETEC-News pull request #25
Opened 2021-05-14 04:53 UTC by memo-saldana

2021-05-14 04:54 UTC, memo-saldana commented
Tackles #16  and #17.

Also creates base user model, for reference with events.

2021-05-14 17:03 UTC, Adrian-Garcia requested changes
Se ve cool. No es necesario que cambies cosas si consideras que deben quedarse. Solo te pediría que si quitaras lo del `role` en el modelo de `user` porque se me hace que es casi 100% seguro de que no se usará

2021-05-14 17:03 UTC, Adrian-Garcia commented on server/models/event.js
> +module.exports = mongoose.model('Event', eventSchema);
Igual y esto es un poco extra pero, ¿crees que puedas poner un salto de linea al final de todos los archivos? 😅 Tengo compu linux y a veces se vuelve loca cuando no tiene el salto de linea y estoy usando vim o nano. Los archivos que no tienen salto de linea se ven con el simbolo rojo 
![Screenshot from 2021-05-14 11-59-44](https://user-images.githubusercontent.com/31387681/118304133-e5a2ef80-b4ab-11eb-8c20-80c9a5050297.png)

2021-05-15 00:23 UTC, memo-saldana commented on package.json
> +    "devServer": "nodemon server/app.js",
Esto pasa porque necesitas la password de MongoDB, se las paso por whatsapp

2021-05-15 00:53 UTC, memo-saldana commented on server/models/user.js
> +  role: {
Seguro que no se necesitará rol de administrador? Por lo que leí la docs algun usuario debe tener el poder de crear eventos no?

2021-05-15 01:03 UTC, memo-saldana commented on server/models/event.js
> +module.exports = mongoose.model('Event', eventSchema);
Listo, agregue en todos los archivos

2021-05-15 01:04 UTC, memo-saldana commented on server/models/user.js
> +  // TODO: validation A00000000
Agregado

2021-05-15 01:07 UTC, Adrian-Garcia commented on package.json
> +    "devServer": "nodemon server/app.js",
¡Gracias!

2021-05-15 01:09 UTC, Adrian-Garcia commented on server/models/user.js
> +  role: {
La idea original sí era esa pero para simplificar el trabajo, @PauCamaraV y yo consideramos implementar otra solución para la creación de eventos. Solo que no está 100% definida todavía. La explico en el siguiente sprint cuando ya esté definida 😃

2021-05-15 01:12 UTC, memo-saldana commented on server/models/user.js
> +  role: {
Listo!

2021-05-15 18:35 UTC, Adrian-Garcia approved these changes
N🧊

2021-05-16 19:48 UTC, merged