Hacer reservaciones v1
APIStear/FETEC-News pull request #32
Opened 2021-05-22 22:45 UTC by moyfdzz

2021-05-22 23:00 UTC, memo-saldana requested changes

2021-05-22 23:00 UTC, memo-saldana commented on server/models/event.js
> +  event.RSVPlist.push(user.id);
yo normalmente utilizaria `user._id` pero si te agrega correctamente el id esta perfecto

2021-05-22 23:09 UTC, PauCamaraV commented on server/routes/event.js
Si hay un requerimiento de cancelar RSVP pero lo dejamos como Nice to Have (solo en caso de que acabemos lo prioritario)
[Caso 18: Cancelar RSVP](https://docs.google.com/document/d/1qQ-DFRHCenrJA7sKQT7dy2kAIm0xzYC_ozEuh9Y48jw/edit#bookmark=id.fogwlha4hh3o)

En resumen no pasa nada si no se hace ahorita.

2021-05-22 23:13 UTC, memo-saldana commented on server/routes/event.js
Va perfecto, lo dejamos pendiente entonces

2021-05-24 17:05 UTC, memo-saldana approved these changes

2021-05-24 17:05 UTC, memo-saldana commented
LGTM!

2021-05-24 17:06 UTC, memo-saldana commented
Avisanos por whatsapp cuando lo mergees porfa, para rebasear los demas branches

2021-05-24 22:02 UTC, merged