Added basic structure
APIStear/FETEC-News pull request #36
Opened 2021-05-25 14:49 UTC by Adrian-Garcia

[FETEC News- #5](https://github.com/APIStear/FETEC-News/issues/5)

## Descripción
Crea eventos

2021-05-26 02:13 UTC, memo-saldana requested changes
Es buen incio, pero estaria cool usar componentes de Material UI para que se vea mas en serio

2021-05-26 02:13 UTC, memo-saldana commented on client/src/EventNew.js
> +        <Button variant="contained" color="primary" className={classes.spacingTop} onClick={_createEvent}>
Le podrias poner spacing abajo del boton? Esta pegado al footer
Tambien se veria mejor con la letra blanca del boton.

2021-05-26 02:13 UTC, memo-saldana commented on client/src/EventNew.js
> +          <TextField id="imgKeys" fullWidth label="URL de fotos"/>
Este campo debe tener algo para explicar el hecho de que los urls deben ir separados por espacios.

En mi opinion, podriamos poner un campo dinamico, en el que se agreguen mas espacios para agregar los links, o que se vean separados cada vez que se agreguen (como cuando pones correos destinatarios en gmail) Algo como [esto](https://material-ui.com/components/chips/)

2021-05-26 02:13 UTC, memo-saldana commented on client/src/EventNew.js
> +          <TextField id="startDate" fullWidth label="Fecha de Inicio"/>
startDate y endDate deberian tener [DatePickers](https://material-ui.com/components/pickers/)

2021-05-26 02:30 UTC, memo-saldana commented
Sorry tampoco vi que aun no estaba listo

2021-05-26 19:40 UTC, Adrian-Garcia commented
> Sorry tampoco vi que aun no estaba listo

Jaja ntp. La parte del diseño no la estoy haciendo yo pero ya casi está 🤠

2021-05-31 18:11 UTC, NataliaMGonzalez commented on client/src/EventNew.js
> +          <TextField id="startDate" fullWidth label="Fecha de Inicio"/>
Esto ya quedó

2021-05-31 18:15 UTC, NataliaMGonzalez commented on client/src/EventNew.js
> +        <Button variant="contained" color="primary" className={classes.spacingTop} onClick={_createEvent}>
Listo

2021-05-31 18:16 UTC, NataliaMGonzalez commented
![newEvent](https://user-images.githubusercontent.com/31547258/120229281-6551ed80-c212-11eb-8cbc-c2a5ec2a9d2a.PNG)

2021-05-31 23:25 UTC, memo-saldana approved these changes
Les quedo muy cool.

Le puse un comentario, si crees que lo puedes hacer sin que te quite mucho tiempo adelante pero no es para nada necesario.

2021-05-31 23:25 UTC, memo-saldana commented on client/src/EventNew.js
> +              <TextField id="imgKeys" fullWidth label="URL de fotos"/>
En el placeholder estaria bien poner que los urls deben ir separados por un espacio, para que sepan de alguna manera que pueden poner varios

2021-05-31 23:25 UTC, memo-saldana commented
Solo recuerden darle merge a `all-events` antes de mergear esta a `main`

2021-05-31 23:59 UTC, NataliaMGonzalez commented on client/src/EventNew.js
> +              <TextField id="imgKeys" fullWidth label="URL de fotos"/>
Le puse un toolTip
![image](https://user-images.githubusercontent.com/31547258/120249992-40756e80-c242-11eb-9ed6-da2839bbfb64.png)

2021-06-01 04:10 UTC, merged